new module LadarSim

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -930,6 +930,8 @@ CONFIG_RACK_LADAR_SICK_S_TRUE
 CONFIG_RACK_LADAR_SICK_S_FALSE
 CONFIG_RACK_LADAR_SICK_LMS100_TRUE
 CONFIG_RACK_LADAR_SICK_LMS100_FALSE
+CONFIG_RACK_LADAR_SIM_TRUE
+CONFIG_RACK_LADAR_SIM_FALSE
 CONFIG_RACK_ODOMETRY_CHASSIS_TRUE
 CONFIG_RACK_ODOMETRY_CHASSIS_FALSE
 CONFIG_RACK_PILOT_JOYSTICK_TRUE
@@ -1673,6 +1675,7 @@ Optional Features:
   --enable-ladar-sick-s   building LadarSickS
   --enable-ladar-sick-lms100
                           building LadarSickLms100
+  --enable-ladar-sim      building LadarSim
   --enable-odometry-chassis
                           building OdometryChassis
   --enable-pilot-joystick building PilotJoystick
@@ -5112,7 +5115,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5115 "configure"' > conftest.$ac_ext
+  echo '#line 5118 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7377,11 +7380,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7380: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7383: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7384: \$? = $ac_status" >&5
+   echo "$as_me:7387: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7667,11 +7670,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7670: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7673: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7674: \$? = $ac_status" >&5
+   echo "$as_me:7677: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7771,11 +7774,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7774: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7777: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7778: \$? = $ac_status" >&5
+   echo "$as_me:7781: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10120,7 +10123,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10123 "configure"
+#line 10126 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10220,7 +10223,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10223 "configure"
+#line 10226 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12640,11 +12643,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12643: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12646: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12647: \$? = $ac_status" >&5
+   echo "$as_me:12650: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12744,11 +12747,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12747: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12750: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12751: \$? = $ac_status" >&5
+   echo "$as_me:12754: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14306,11 +14309,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14309: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14312: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14313: \$? = $ac_status" >&5
+   echo "$as_me:14316: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14410,11 +14413,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14413: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14416: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14417: \$? = $ac_status" >&5
+   echo "$as_me:14420: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16597,11 +16600,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16600: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16603: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16604: \$? = $ac_status" >&5
+   echo "$as_me:16607: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16887,11 +16890,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16890: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16893: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16894: \$? = $ac_status" >&5
+   echo "$as_me:16897: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16991,11 +16994,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16994: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16997: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16998: \$? = $ac_status" >&5
+   echo "$as_me:17001: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21099,6 +21102,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build LadarSim" >&5
+echo $ECHO_N "checking build LadarSim... $ECHO_C" >&6; }
+# Check whether --enable-ladar-sm was given.
+if test "${enable_ladar_sm+set}" = set; then
+  enableval=$enable_ladar_sm; case "$enableval" in
+        y | yes) CONFIG_RACK_LADAR_SIM=y ;;
+        *) CONFIG_RACK_LADAR_SIM=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_LADAR_SIM:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_LADAR_SIM:-n}" >&6; }
+ if test "$CONFIG_RACK_LADAR_SIM" = "y"; then
+  CONFIG_RACK_LADAR_SIM_TRUE=
+  CONFIG_RACK_LADAR_SIM_FALSE='#'
+else
+  CONFIG_RACK_LADAR_SIM_TRUE='#'
+  CONFIG_RACK_LADAR_SIM_FALSE=
+fi
+
+if test "$CONFIG_RACK_LADAR_SIM" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_LADAR_SIM 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build OdometryChassis" >&5
 echo $ECHO_N "checking build OdometryChassis... $ECHO_C" >&6; }
 # Check whether --enable-odometry-chassis was given.
@@ -24369,6 +24401,13 @@ echo "$as_me: error: conditional \"CONFIG_RACK_LADAR_SICK_LMS100\" was never def
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RACK_LADAR_SIM_TRUE}" && test -z "${CONFIG_RACK_LADAR_SIM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_LADAR_SIM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_LADAR_SIM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RACK_ODOMETRY_CHASSIS_TRUE}" && test -z "${CONFIG_RACK_ODOMETRY_CHASSIS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_ODOMETRY_CHASSIS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -25351,6 +25390,8 @@ CONFIG_RACK_LADAR_SICK_S_TRUE!$CONFIG_RACK_LADAR_SICK_S_TRUE$ac_delim
 CONFIG_RACK_LADAR_SICK_S_FALSE!$CONFIG_RACK_LADAR_SICK_S_FALSE$ac_delim
 CONFIG_RACK_LADAR_SICK_LMS100_TRUE!$CONFIG_RACK_LADAR_SICK_LMS100_TRUE$ac_delim
 CONFIG_RACK_LADAR_SICK_LMS100_FALSE!$CONFIG_RACK_LADAR_SICK_LMS100_FALSE$ac_delim
+CONFIG_RACK_LADAR_SIM_TRUE!$CONFIG_RACK_LADAR_SIM_TRUE$ac_delim
+CONFIG_RACK_LADAR_SIM_FALSE!$CONFIG_RACK_LADAR_SIM_FALSE$ac_delim
 CONFIG_RACK_ODOMETRY_CHASSIS_TRUE!$CONFIG_RACK_ODOMETRY_CHASSIS_TRUE$ac_delim
 CONFIG_RACK_ODOMETRY_CHASSIS_FALSE!$CONFIG_RACK_ODOMETRY_CHASSIS_FALSE$ac_delim
 CONFIG_RACK_PILOT_JOYSTICK_TRUE!$CONFIG_RACK_PILOT_JOYSTICK_TRUE$ac_delim
@@ -25381,8 +25422,6 @@ CONFIG_DATALOG_REC_TRUE!$CONFIG_DATALOG_REC_TRUE$ac_delim
 CONFIG_DATALOG_REC_FALSE!$CONFIG_DATALOG_REC_FALSE$ac_delim
 XENOMAI_CPPFLAGS!$XENOMAI_CPPFLAGS$ac_delim
 XENOMAI_LDFLAGS!$XENOMAI_LDFLAGS$ac_delim
-XENOMAI_LIBS!$XENOMAI_LIBS$ac_delim
-CONFIG_RACK_OS_XENOMAI_TRUE!$CONFIG_RACK_OS_XENOMAI_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -25424,6 +25463,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XENOMAI_LIBS!$XENOMAI_LIBS$ac_delim
+CONFIG_RACK_OS_XENOMAI_TRUE!$CONFIG_RACK_OS_XENOMAI_TRUE$ac_delim
 CONFIG_RACK_OS_XENOMAI_FALSE!$CONFIG_RACK_OS_XENOMAI_FALSE$ac_delim
 LINUX_CPPFLAGS!$LINUX_CPPFLAGS$ac_delim
 LINUX_LDFLAGS!$LINUX_LDFLAGS$ac_delim
@@ -25493,7 +25534,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 67; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
