Added libusb support.

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -1009,6 +1009,11 @@ CONFIG_GSL_TRUE
 CONFIG_GSL_FALSE
 CONFIG_RACK_GSL_SUPPORT_TRUE
 CONFIG_RACK_GSL_SUPPORT_FALSE
+LIBUSB_CPPFLAGS
+LIBUSB_LDFLAGS
+LIBUSB_LIBS
+CONFIG_RACK_LIBUSB_SUPPORT_TRUE
+CONFIG_RACK_LIBUSB_SUPPORT_FALSE
 RACK_GLOBAL_CPPFLAGS
 RACK_GLOBAL_LDFLAGS
 RACK_CPPFLAGS
@@ -1647,6 +1652,7 @@ Optional Features:
   --enable-libpng-support enable libpng support
   --enable-opencv-support enable opencv support
   --enable-gsl-support    enable gsl support
+  --enable-libusb-support enable libusb support
   --enable-java           building java
   --enable-java-gui       building java gui
   --enable-camera-dcam    building CameraDcam
@@ -1724,6 +1730,8 @@ Optional Packages:
   --with-opencv=<opencv-dir>
                           Install directory of opencv
   --with-gsl=<gsl-dir>    Install directory of gsl
+  --with-libusb=<libusb-dir>
+                          Install directory of libusb
   --with-module-dir=<module-dir>
                           Installation directory for modules
 
@@ -5115,7 +5123,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5118 "configure"' > conftest.$ac_ext
+  echo '#line 5126 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7380,11 +7388,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7383: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7391: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7387: \$? = $ac_status" >&5
+   echo "$as_me:7395: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7670,11 +7678,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7673: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7681: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7677: \$? = $ac_status" >&5
+   echo "$as_me:7685: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7774,11 +7782,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7777: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7785: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7781: \$? = $ac_status" >&5
+   echo "$as_me:7789: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10123,7 +10131,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10126 "configure"
+#line 10134 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10223,7 +10231,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10226 "configure"
+#line 10234 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12643,11 +12651,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12646: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12654: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12650: \$? = $ac_status" >&5
+   echo "$as_me:12658: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12747,11 +12755,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12750: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12758: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12754: \$? = $ac_status" >&5
+   echo "$as_me:12762: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14309,11 +14317,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14312: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14320: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14316: \$? = $ac_status" >&5
+   echo "$as_me:14324: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14413,11 +14421,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14416: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14424: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14420: \$? = $ac_status" >&5
+   echo "$as_me:14428: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16600,11 +16608,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16603: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16611: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16607: \$? = $ac_status" >&5
+   echo "$as_me:16615: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16890,11 +16898,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16893: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16901: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16897: \$? = $ac_status" >&5
+   echo "$as_me:16905: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16994,11 +17002,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17005: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17001: \$? = $ac_status" >&5
+   echo "$as_me:17009: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20454,6 +20462,31 @@ fi
 
 
 
+# Check whether --enable-libusb-support was given.
+if test "${enable_libusb_support+set}" = set; then
+  enableval=$enable_libusb_support; case "$enableval" in
+        y | yes) CONFIG_RACK_LIBUSB_SUPPORT=y ;;
+        *) CONFIG_RACK_LIBUSB_SUPPORT=n ;;
+    esac
+fi
+
+
+
+# Check whether --with-libusb-dir was given.
+if test "${with_libusb_dir+set}" = set; then
+  withval=$with_libusb_dir; case "${withval}" in
+        "" | y | ye | yes | n | no)
+            { { echo "$as_me:$LINENO: error: You must supply an argument to --with-libusb." >&5
+echo "$as_me: error: You must supply an argument to --with-libusb." >&2;}
+   { (exit 1); exit 1; }; }
+      ;;
+    esac
+    CONFIG_RACK_LIBUSBDIR="$withval"
+
+fi
+
+
+
 
 { echo "$as_me:$LINENO: checking build java" >&5
 echo $ECHO_N "checking build java... $ECHO_C" >&6; }
@@ -23812,6 +23845,272 @@ fi
 
 
 
+{ echo "$as_me:$LINENO: checking libusb support" >&5
+echo $ECHO_N "checking libusb support... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_LIBUSB_SUPPORT}" >&5
+echo "${ECHO_T}${CONFIG_RACK_LIBUSB_SUPPORT}" >&6; }
+
+LIBUSB_CPPFLAGS=""
+LIBUSB_LDFLAGS=""
+LIBUSB_LIBS=""
+
+if test x"${CONFIG_RACK_LIBUSB_SUPPORT}" = x"y"; then
+
+    cppflags_backup="${CPPFLAGS}"
+    ldflags_backup="${LDFLAGS}"
+    libs_backup="${LIBS}"
+
+    if test x${CONFIG_RACK_LIBUSBDIR} != "x"; then
+        { echo "$as_me:$LINENO: checking libusb directory" >&5
+echo $ECHO_N "checking libusb directory... $ECHO_C" >&6; }
+        if test -d ${CONFIG_RACK_LIBUSBDIR}; then
+            { echo "$as_me:$LINENO: result: ${CONFIG_RACK_LIBUSBDIR}" >&5
+echo "${ECHO_T}${CONFIG_RACK_LIBUSBDIR}" >&6; }
+
+            LIBUSB_CPPFLAGS="-I${CONFIG_RACK_LIBUSBDIR}/include/libusb-1.0"
+            LIBUSB_LDFLAGS="-L${CONFIG_RACK_LIBUSBDIR}/lib -Wl,-rpath=${CONFIG_RACK_LIBUSBDIR}/lib"
+            LIBUSB_LIBS="-lusb"
+
+            CPPFLAGS="${LIBUSB_CPPFLAGS} ${CPPFLAGS}"
+            LDFLAGS="${LIBUSB_LDFLAGS} ${LDFLAGS}"
+            LIBS="$LIBUSB_LIBS"
+        else
+            { { echo "$as_me:$LINENO: error: cannot find ${CONFIG_RACK_LIBUSBDIR}" >&5
+echo "$as_me: error: cannot find ${CONFIG_RACK_LIBUSBDIR}" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+
+    if test "${ac_cv_header_libusb_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for libusb.h" >&5
+echo $ECHO_N "checking for libusb.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_libusb_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_libusb_h" >&5
+echo "${ECHO_T}$ac_cv_header_libusb_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking libusb.h usability" >&5
+echo $ECHO_N "checking libusb.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <libusb.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking libusb.h presence" >&5
+echo $ECHO_N "checking libusb.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libusb.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: libusb.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: libusb.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: libusb.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: libusb.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: libusb.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: libusb.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: libusb.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: libusb.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libusb.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libusb.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: libusb.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for libusb.h" >&5
+echo $ECHO_N "checking for libusb.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_libusb_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_libusb_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_libusb_h" >&5
+echo "${ECHO_T}$ac_cv_header_libusb_h" >&6; }
+
+fi
+if test $ac_cv_header_libusb_h = yes; then
+
+{ echo "$as_me:$LINENO: checking for libusb_get_device_list in -lusb" >&5
+echo $ECHO_N "checking for libusb_get_device_list in -lusb... $ECHO_C" >&6; }
+if test "${ac_cv_lib_usb_libusb_get_device_list+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lusb  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char libusb_get_device_list ();
+int
+main ()
+{
+return libusb_get_device_list ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_usb_libusb_get_device_list=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_usb_libusb_get_device_list=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_usb_libusb_get_device_list" >&5
+echo "${ECHO_T}$ac_cv_lib_usb_libusb_get_device_list" >&6; }
+if test $ac_cv_lib_usb_libusb_get_device_list = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBUSB 1
+_ACEOF
+
+  LIBS="-lusb $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: cannot find function libusb_get_device_list" >&5
+echo "$as_me: error: cannot find function libusb_get_device_list" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+else
+  { { echo "$as_me:$LINENO: error: cannot find libusb header files" >&5
+echo "$as_me: error: cannot find libusb header files" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+
+
+    RACK_SUPPORTS="libusb ${RACK_SUPPORTS}"
+    CPPFLAGS="${cppflags_backup}"
+    LDFLAGS="${ldflags_backup}"
+    LIBS="${libs_backup}"
+fi
+
+
+
+
+ if test x"${CONFIG_RACK_LIBUSB_SUPPORT}" = "xy"; then
+  CONFIG_RACK_LIBUSB_SUPPORT_TRUE=
+  CONFIG_RACK_LIBUSB_SUPPORT_FALSE='#'
+else
+  CONFIG_RACK_LIBUSB_SUPPORT_TRUE='#'
+  CONFIG_RACK_LIBUSB_SUPPORT_FALSE=
+fi
+
+
+
 RACK_GLOBAL_CPPFLAGS="-Wall -pipe -O2 -fstrict-aliasing"
 RACK_GLOBAL_LDFLAGS="--export-dynamic"
 
@@ -24587,6 +24886,13 @@ if test -z "${CONFIG_RACK_GSL_SUPPORT_TRUE}" && test -z "${CONFIG_RACK_GSL_SUPPO
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_GSL_SUPPORT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RACK_GSL_SUPPORT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RACK_LIBUSB_SUPPORT_TRUE}" && test -z "${CONFIG_RACK_LIBUSB_SUPPORT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_LIBUSB_SUPPORT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_LIBUSB_SUPPORT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25510,6 +25816,11 @@ CONFIG_GSL_TRUE!$CONFIG_GSL_TRUE$ac_delim
 CONFIG_GSL_FALSE!$CONFIG_GSL_FALSE$ac_delim
 CONFIG_RACK_GSL_SUPPORT_TRUE!$CONFIG_RACK_GSL_SUPPORT_TRUE$ac_delim
 CONFIG_RACK_GSL_SUPPORT_FALSE!$CONFIG_RACK_GSL_SUPPORT_FALSE$ac_delim
+LIBUSB_CPPFLAGS!$LIBUSB_CPPFLAGS$ac_delim
+LIBUSB_LDFLAGS!$LIBUSB_LDFLAGS$ac_delim
+LIBUSB_LIBS!$LIBUSB_LIBS$ac_delim
+CONFIG_RACK_LIBUSB_SUPPORT_TRUE!$CONFIG_RACK_LIBUSB_SUPPORT_TRUE$ac_delim
+CONFIG_RACK_LIBUSB_SUPPORT_FALSE!$CONFIG_RACK_LIBUSB_SUPPORT_FALSE$ac_delim
 RACK_GLOBAL_CPPFLAGS!$RACK_GLOBAL_CPPFLAGS$ac_delim
 RACK_GLOBAL_LDFLAGS!$RACK_GLOBAL_LDFLAGS$ac_delim
 RACK_CPPFLAGS!$RACK_CPPFLAGS$ac_delim
@@ -25534,7 +25845,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 74; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
