added new module class CLOCK and added module ClockDcf77EmcPro

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -906,6 +906,8 @@ CONFIG_RACK_CHASSIS_SIM_TRUE
 CONFIG_RACK_CHASSIS_SIM_FALSE
 CONFIG_RACK_CHASSIS_ROOMBA_TRUE
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE
+CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE
+CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE
 CONFIG_RACK_GPS_NMEA_TRUE
 CONFIG_RACK_GPS_NMEA_FALSE
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE
@@ -1633,6 +1635,8 @@ Optional Features:
   --enable-chassis-er1    building ChassisEr1
   --enable-chassis-sim    building ChassisSim
   --enable-chassis-roomba building ChassisRoomba
+  --enable-clock-dcf77-emc-pro
+                          building ClockDcf77EmcPro
   --enable-gps-nmea       building GpsNmea
   --enable-ladar-hokuyo-urg
                           building LadarHokuyoUrg
@@ -4605,7 +4609,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4608 "configure"' > conftest.$ac_ext
+  echo '#line 4612 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7342,11 +7346,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7345: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7349: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7349: \$? = $ac_status" >&5
+   echo "$as_me:7353: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7632,11 +7636,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7635: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7639: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7639: \$? = $ac_status" >&5
+   echo "$as_me:7643: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7736,11 +7740,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7739: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7743: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7743: \$? = $ac_status" >&5
+   echo "$as_me:7747: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10085,7 +10089,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10088 "configure"
+#line 10092 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10185,7 +10189,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10188 "configure"
+#line 10192 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12605,11 +12609,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12612: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12612: \$? = $ac_status" >&5
+   echo "$as_me:12616: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12709,11 +12713,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12712: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12716: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12716: \$? = $ac_status" >&5
+   echo "$as_me:12720: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14271,11 +14275,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14274: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14278: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14278: \$? = $ac_status" >&5
+   echo "$as_me:14282: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14375,11 +14379,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14378: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14382: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14382: \$? = $ac_status" >&5
+   echo "$as_me:14386: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16562,11 +16566,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16565: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16569: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16569: \$? = $ac_status" >&5
+   echo "$as_me:16573: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16852,11 +16856,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16855: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16859: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16859: \$? = $ac_status" >&5
+   echo "$as_me:16863: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16956,11 +16960,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16959: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16963: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16963: \$? = $ac_status" >&5
+   echo "$as_me:16967: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20688,6 +20692,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build ClockDcf77EmcPro" >&5
+echo $ECHO_N "checking build ClockDcf77EmcPro... $ECHO_C" >&6; }
+# Check whether --enable-clock-dcf77-emc-pro was given.
+if test "${enable_clock_dcf77_emc_pro+set}" = set; then
+  enableval=$enable_clock_dcf77_emc_pro; case "$enableval" in
+        y | yes) CONFIG_RACK_CLOCK_DCF77_EMC_PRO=y ;;
+        *) CONFIG_RACK_CLOCK_DCF77_EMC_PRO=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_CLOCK_DCF77_EMC_PRO:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_CLOCK_DCF77_EMC_PRO:-n}" >&6; }
+ if test "$CONFIG_RACK_CLOCK_DCF77_EMC_PRO" = "y"; then
+  CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE=
+  CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE='#'
+else
+  CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE='#'
+  CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE=
+fi
+
+if test "$CONFIG_RACK_CLOCK_DCF77_EMC_PRO" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_CLOCK_DCF77_EMC_PRO 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build GpsNmea" >&5
 echo $ECHO_N "checking build GpsNmea... $ECHO_C" >&6; }
 # Check whether --enable-gps-nmea was given.
@@ -23361,7 +23394,7 @@ for DIR in \
 done
 
 
-ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile config/kconfig/GNUmakefile config/kconfig/lxdialog/GNUmakefile main/GNUmakefile main/argopts/GNUmakefile main/defines/GNUmakefile main/dxfmap/GNUmakefile main/lib/GNUmakefile main/mailbox/GNUmakefile main/module/GNUmakefile main/proxy/GNUmakefile main/position_tool/GNUmakefile main/camera_tool/GNUmakefile main/canport/GNUmakefile main/serialport/GNUmakefile main/tims/GNUmakefile main/tims/driver/GNUmakefile main/tims/router/GNUmakefile drivers/GNUmakefile drivers/camera/GNUmakefile drivers/chassis/GNUmakefile drivers/gps/GNUmakefile drivers/ladar/GNUmakefile drivers/odometry/GNUmakefile navigation/GNUmakefile navigation/pilot/GNUmakefile navigation/position/GNUmakefile perception/GNUmakefile perception/scan2d/GNUmakefile perception/obj_recog/GNUmakefile skel/GNUmakefile skel/dummy/GNUmakefile gui/GNUmakefile gui/main/GNUmakefile gui/drivers/GNUmakefile gui/navigation/GNUmakefile gui/perception/GNUmakefile gui/tools/GNUmakefile tools/GNUmakefile tools/datalog/GNUmakefile examples/GNUmakefile examples/load_rack_sim examples/load_rack_gui scripts/GNUmakefile scripts/rack-config"
+ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile config/kconfig/GNUmakefile config/kconfig/lxdialog/GNUmakefile main/GNUmakefile main/argopts/GNUmakefile main/defines/GNUmakefile main/dxfmap/GNUmakefile main/lib/GNUmakefile main/mailbox/GNUmakefile main/module/GNUmakefile main/proxy/GNUmakefile main/position_tool/GNUmakefile main/camera_tool/GNUmakefile main/canport/GNUmakefile main/serialport/GNUmakefile main/tims/GNUmakefile main/tims/driver/GNUmakefile main/tims/router/GNUmakefile drivers/GNUmakefile drivers/camera/GNUmakefile drivers/chassis/GNUmakefile drivers/clock/GNUmakefile drivers/gps/GNUmakefile drivers/ladar/GNUmakefile drivers/odometry/GNUmakefile navigation/GNUmakefile navigation/pilot/GNUmakefile navigation/position/GNUmakefile perception/GNUmakefile perception/scan2d/GNUmakefile perception/obj_recog/GNUmakefile skel/GNUmakefile skel/dummy/GNUmakefile gui/GNUmakefile gui/main/GNUmakefile gui/drivers/GNUmakefile gui/navigation/GNUmakefile gui/perception/GNUmakefile gui/tools/GNUmakefile tools/GNUmakefile tools/datalog/GNUmakefile examples/GNUmakefile examples/load_rack_sim examples/load_rack_gui scripts/GNUmakefile scripts/rack-config"
 
 
 if test \! x$RACK_MAYBE_DOCDIR = x; then
@@ -23577,6 +23610,13 @@ if test -z "${CONFIG_RACK_CHASSIS_ROOMBA_TRUE}" && test -z "${CONFIG_RACK_CHASSI
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CHASSIS_ROOMBA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RACK_CHASSIS_ROOMBA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE}" && test -z "${CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CLOCK_DCF77_EMC_PRO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_DCF77_EMC_PRO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24287,6 +24327,7 @@ do
     "drivers/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/GNUmakefile" ;;
     "drivers/camera/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/camera/GNUmakefile" ;;
     "drivers/chassis/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/chassis/GNUmakefile" ;;
+    "drivers/clock/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/clock/GNUmakefile" ;;
     "drivers/gps/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/gps/GNUmakefile" ;;
     "drivers/ladar/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/ladar/GNUmakefile" ;;
     "drivers/odometry/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/odometry/GNUmakefile" ;;
@@ -24558,6 +24599,8 @@ CONFIG_RACK_CHASSIS_SIM_TRUE!$CONFIG_RACK_CHASSIS_SIM_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_SIM_FALSE!$CONFIG_RACK_CHASSIS_SIM_FALSE$ac_delim
 CONFIG_RACK_CHASSIS_ROOMBA_TRUE!$CONFIG_RACK_CHASSIS_ROOMBA_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE!$CONFIG_RACK_CHASSIS_ROOMBA_FALSE$ac_delim
+CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE$ac_delim
+CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE$ac_delim
 CONFIG_RACK_GPS_NMEA_TRUE!$CONFIG_RACK_GPS_NMEA_TRUE$ac_delim
 CONFIG_RACK_GPS_NMEA_FALSE!$CONFIG_RACK_GPS_NMEA_FALSE$ac_delim
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE!$CONFIG_RACK_LADAR_HOKUYO_URG_TRUE$ac_delim
@@ -24612,8 +24655,6 @@ CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
 LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
 LIBRAW1394_LDFLAGS!$LIBRAW1394_LDFLAGS$ac_delim
 LIBRAW1394_LIBS!$LIBRAW1394_LIBS$ac_delim
-CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE!$CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE$ac_delim
-CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE!$CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24655,6 +24696,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE!$CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE$ac_delim
+CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE!$CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE$ac_delim
 LIBDC1394_CPPFLAGS!$LIBDC1394_CPPFLAGS$ac_delim
 LIBDC1394_LDFLAGS!$LIBDC1394_LDFLAGS$ac_delim
 LIBDC1394_LIBS!$LIBDC1394_LIBS$ac_delim
@@ -24703,7 +24746,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 46; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 48; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
