added new module class COMPASS and module CompassCmps03

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -914,6 +914,8 @@ CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE
 CONFIG_RACK_CLOCK_SYSTEM_TRUE
 CONFIG_RACK_CLOCK_SYSTEM_FALSE
+CONFIG_RACK_COMPASS_CMPS03_TRUE
+CONFIG_RACK_COMPASS_CMPS03_FALSE
 CONFIG_RACK_GPS_NMEA_TRUE
 CONFIG_RACK_GPS_NMEA_FALSE
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE
@@ -1660,6 +1662,7 @@ Optional Features:
   --enable-clock-dcf77-mbg-c51
                           building ClockDcf77MbgC51
   --enable-clock-system   building ClockSystem
+  --enable-compass-cmps03 building CompassCmps03
   --enable-gps-nmea       building GpsNmea
   --enable-ladar-hokuyo-urg
                           building LadarHokuyoUrg
@@ -5109,7 +5112,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5112 "configure"' > conftest.$ac_ext
+  echo '#line 5115 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7374,11 +7377,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7377: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7380: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7381: \$? = $ac_status" >&5
+   echo "$as_me:7384: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7664,11 +7667,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7667: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7670: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7671: \$? = $ac_status" >&5
+   echo "$as_me:7674: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7768,11 +7771,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7771: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7774: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7775: \$? = $ac_status" >&5
+   echo "$as_me:7778: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10117,7 +10120,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10120 "configure"
+#line 10123 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10217,7 +10220,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10220 "configure"
+#line 10223 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12637,11 +12640,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12640: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12643: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12644: \$? = $ac_status" >&5
+   echo "$as_me:12647: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12741,11 +12744,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12744: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12747: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12748: \$? = $ac_status" >&5
+   echo "$as_me:12751: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14303,11 +14306,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14306: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14309: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14310: \$? = $ac_status" >&5
+   echo "$as_me:14313: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14407,11 +14410,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14410: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14413: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14414: \$? = $ac_status" >&5
+   echo "$as_me:14417: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16594,11 +16597,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16600: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16601: \$? = $ac_status" >&5
+   echo "$as_me:16604: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16884,11 +16887,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16887: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16890: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16891: \$? = $ac_status" >&5
+   echo "$as_me:16894: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16988,11 +16991,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16991: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16994: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16995: \$? = $ac_status" >&5
+   echo "$as_me:16998: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20861,6 +20864,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build CompassCmps03" >&5
+echo $ECHO_N "checking build CompassCmps03... $ECHO_C" >&6; }
+# Check whether --enable-compass-cmps03 was given.
+if test "${enable_compass_cmps03+set}" = set; then
+  enableval=$enable_compass_cmps03; case "$enableval" in
+        y | yes) CONFIG_RACK_COMPASS_CMPOS03=y ;;
+        *) CONFIG_RACK_COMPASS_CMPS03=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_COMPASS_CMPS03:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_COMPASS_CMPS03:-n}" >&6; }
+ if test "$CONFIG_RACK_COMPASS_CMPS03" = "y"; then
+  CONFIG_RACK_COMPASS_CMPS03_TRUE=
+  CONFIG_RACK_COMPASS_CMPS03_FALSE='#'
+else
+  CONFIG_RACK_COMPASS_CMPS03_TRUE='#'
+  CONFIG_RACK_COMPASS_CMPS03_FALSE=
+fi
+
+if test "$CONFIG_RACK_COMPASS_CMPS03" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_COMPASS_CMPS03 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build GpsNmea" >&5
 echo $ECHO_N "checking build GpsNmea... $ECHO_C" >&6; }
 # Check whether --enable-gps-nmea was given.
@@ -24031,7 +24063,7 @@ for DIR in \
 done
 
 
-ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile config/kconfig/GNUmakefile config/kconfig/lxdialog/GNUmakefile main/GNUmakefile main/defines/GNUmakefile main/lib/GNUmakefile main/tools/GNUmakefile main/common/GNUmakefile main/xenomai/GNUmakefile main/linux/GNUmakefile main/tims/GNUmakefile main/tims/xenomai/GNUmakefile main/tims/xenomai_kmod/GNUmakefile main/tims/linux/GNUmakefile main/tims/router/GNUmakefile control/GNUmakefile drivers/GNUmakefile drivers/camera/GNUmakefile drivers/chassis/GNUmakefile drivers/clock/GNUmakefile drivers/gps/GNUmakefile drivers/ladar/GNUmakefile navigation/GNUmakefile navigation/odometry/GNUmakefile navigation/pilot/GNUmakefile navigation/position/GNUmakefile perception/GNUmakefile perception/scan2d/GNUmakefile perception/obj_recog/GNUmakefile skel/GNUmakefile skel/dummy/GNUmakefile gui/GNUmakefile gui/main/GNUmakefile gui/control/GNUmakefile gui/drivers/GNUmakefile gui/navigation/GNUmakefile gui/perception/GNUmakefile gui/tools/GNUmakefile tools/GNUmakefile tools/datalog/GNUmakefile examples/GNUmakefile examples/load_rack_sim examples/load_rack_gui scripts/GNUmakefile scripts/rack-config"
+ac_config_files="$ac_config_files GNUmakefile config/GNUmakefile config/kconfig/GNUmakefile config/kconfig/lxdialog/GNUmakefile main/GNUmakefile main/defines/GNUmakefile main/lib/GNUmakefile main/tools/GNUmakefile main/common/GNUmakefile main/xenomai/GNUmakefile main/linux/GNUmakefile main/tims/GNUmakefile main/tims/xenomai/GNUmakefile main/tims/xenomai_kmod/GNUmakefile main/tims/linux/GNUmakefile main/tims/router/GNUmakefile control/GNUmakefile drivers/GNUmakefile drivers/camera/GNUmakefile drivers/chassis/GNUmakefile drivers/clock/GNUmakefile drivers/compass/GNUmakefile drivers/gps/GNUmakefile drivers/ladar/GNUmakefile navigation/GNUmakefile navigation/odometry/GNUmakefile navigation/pilot/GNUmakefile navigation/position/GNUmakefile perception/GNUmakefile perception/scan2d/GNUmakefile perception/obj_recog/GNUmakefile skel/GNUmakefile skel/dummy/GNUmakefile gui/GNUmakefile gui/main/GNUmakefile gui/control/GNUmakefile gui/drivers/GNUmakefile gui/navigation/GNUmakefile gui/perception/GNUmakefile gui/tools/GNUmakefile tools/GNUmakefile tools/datalog/GNUmakefile examples/GNUmakefile examples/load_rack_sim examples/load_rack_gui scripts/GNUmakefile scripts/rack-config"
 
 
 if test \! x$RACK_MAYBE_DOCDIR = x; then
@@ -24275,6 +24307,13 @@ if test -z "${CONFIG_RACK_CLOCK_SYSTEM_TRUE}" && test -z "${CONFIG_RACK_CLOCK_SY
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CLOCK_SYSTEM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_SYSTEM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RACK_COMPASS_CMPS03_TRUE}" && test -z "${CONFIG_RACK_COMPASS_CMPS03_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_COMPASS_CMPS03\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_COMPASS_CMPS03\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25012,6 +25051,7 @@ do
     "drivers/camera/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/camera/GNUmakefile" ;;
     "drivers/chassis/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/chassis/GNUmakefile" ;;
     "drivers/clock/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/clock/GNUmakefile" ;;
+    "drivers/compass/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/compass/GNUmakefile" ;;
     "drivers/gps/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/gps/GNUmakefile" ;;
     "drivers/ladar/GNUmakefile") CONFIG_FILES="$CONFIG_FILES drivers/ladar/GNUmakefile" ;;
     "navigation/GNUmakefile") CONFIG_FILES="$CONFIG_FILES navigation/GNUmakefile" ;;
@@ -25292,6 +25332,8 @@ CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE$ac_de
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE$ac_delim
 CONFIG_RACK_CLOCK_SYSTEM_TRUE!$CONFIG_RACK_CLOCK_SYSTEM_TRUE$ac_delim
 CONFIG_RACK_CLOCK_SYSTEM_FALSE!$CONFIG_RACK_CLOCK_SYSTEM_FALSE$ac_delim
+CONFIG_RACK_COMPASS_CMPS03_TRUE!$CONFIG_RACK_COMPASS_CMPS03_TRUE$ac_delim
+CONFIG_RACK_COMPASS_CMPS03_FALSE!$CONFIG_RACK_COMPASS_CMPS03_FALSE$ac_delim
 CONFIG_RACK_GPS_NMEA_TRUE!$CONFIG_RACK_GPS_NMEA_TRUE$ac_delim
 CONFIG_RACK_GPS_NMEA_FALSE!$CONFIG_RACK_GPS_NMEA_FALSE$ac_delim
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE!$CONFIG_RACK_LADAR_HOKUYO_URG_TRUE$ac_delim
@@ -25338,8 +25380,6 @@ XENOMAI_CPPFLAGS!$XENOMAI_CPPFLAGS$ac_delim
 XENOMAI_LDFLAGS!$XENOMAI_LDFLAGS$ac_delim
 XENOMAI_LIBS!$XENOMAI_LIBS$ac_delim
 CONFIG_RACK_OS_XENOMAI_TRUE!$CONFIG_RACK_OS_XENOMAI_TRUE$ac_delim
-CONFIG_RACK_OS_XENOMAI_FALSE!$CONFIG_RACK_OS_XENOMAI_FALSE$ac_delim
-LINUX_CPPFLAGS!$LINUX_CPPFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -25381,6 +25421,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CONFIG_RACK_OS_XENOMAI_FALSE!$CONFIG_RACK_OS_XENOMAI_FALSE$ac_delim
+LINUX_CPPFLAGS!$LINUX_CPPFLAGS$ac_delim
 LINUX_LDFLAGS!$LINUX_LDFLAGS$ac_delim
 LINUX_LIBS!$LINUX_LIBS$ac_delim
 CONFIG_RACK_OS_LINUX_TRUE!$CONFIG_RACK_OS_LINUX_TRUE$ac_delim
@@ -25448,7 +25490,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 65; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 67; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
