added new module ObjRecogIbeoLux for CAN communication with ibeo lux

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -948,6 +948,8 @@ CONFIG_RACK_SCAN2D_SIM_TRUE
 CONFIG_RACK_SCAN2D_SIM_FALSE
 CONFIG_RACK_SCAN2D_LAB_TRUE
 CONFIG_RACK_SCAN2D_LAB_FALSE
+CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE
+CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE
 CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_TRUE
 CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_FALSE
 CONFIG_RACK_DUMMY_ABC_TRUE
@@ -1681,6 +1683,8 @@ Optional Features:
   --enable-scan2d-merge   building Scan2dMerge
   --enable-scan2d-sim     building Scan2dSim
   --enable-scan2d-lab     building Scan2dLab
+  --enable-obj-recog-ibeo-lux
+                          building ObjRecogIbeoLux
   --enable-obj-recog-relay-ladar
                           building ObjRecogRelayLadar
   --enable-dummy-abc      building DummyAbc
@@ -5105,7 +5109,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5108 "configure"' > conftest.$ac_ext
+  echo '#line 5112 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7370,11 +7374,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7373: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7377: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7377: \$? = $ac_status" >&5
+   echo "$as_me:7381: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7660,11 +7664,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7663: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7667: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7667: \$? = $ac_status" >&5
+   echo "$as_me:7671: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7764,11 +7768,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7767: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7771: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7771: \$? = $ac_status" >&5
+   echo "$as_me:7775: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10113,7 +10117,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10116 "configure"
+#line 10120 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10213,7 +10217,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10216 "configure"
+#line 10220 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12633,11 +12637,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12636: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12640: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12640: \$? = $ac_status" >&5
+   echo "$as_me:12644: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12737,11 +12741,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12740: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12744: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12744: \$? = $ac_status" >&5
+   echo "$as_me:12748: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14299,11 +14303,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14302: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14306: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14306: \$? = $ac_status" >&5
+   echo "$as_me:14310: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14403,11 +14407,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14406: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14410: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14410: \$? = $ac_status" >&5
+   echo "$as_me:14414: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16590,11 +16594,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16593: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16597: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16597: \$? = $ac_status" >&5
+   echo "$as_me:16601: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16880,11 +16884,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16883: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16887: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16887: \$? = $ac_status" >&5
+   echo "$as_me:16891: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16984,11 +16988,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16987: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16991: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16991: \$? = $ac_status" >&5
+   echo "$as_me:16995: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21351,6 +21355,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build ObjRecogIbeoLux" >&5
+echo $ECHO_N "checking build ObjRecogIbeoLux... $ECHO_C" >&6; }
+# Check whether --enable-obj-recog-ibeo-lux was given.
+if test "${enable_obj_recog_ibeo_lux+set}" = set; then
+  enableval=$enable_obj_recog_ibeo_lux; case "$enableval" in
+        y | yes) CONFIG_RACK_OBJ_RECOG_IBEO_LUX=y ;;
+        *) CONFIG_RACK_OBJ_RECOG_IBEO_LUX=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_OBJ_RECOG_IBEO_LUX:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_OBJ_RECOG_IBEO_LUX:-n}" >&6; }
+ if test "$CONFIG_RACK_OBJ_RECOG_IBEO_LUX" = "y"; then
+  CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE=
+  CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE='#'
+else
+  CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE='#'
+  CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE=
+fi
+
+if test "$CONFIG_RACK_OBJ_RECOG_IBEO_LUX" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_OBJ_RECOG_IBEO_LUX 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build ObjRecogRelayLadar" >&5
 echo $ECHO_N "checking build ObjRecogRelayLadar... $ECHO_C" >&6; }
 # Check whether --enable-obj-recog-relay-ladar was given.
@@ -24364,6 +24397,13 @@ echo "$as_me: error: conditional \"CONFIG_RACK_SCAN2D_LAB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE}" && test -z "${CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_OBJ_RECOG_IBEO_LUX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_OBJ_RECOG_IBEO_LUX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_TRUE}" && test -z "${CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_OBJ_RECOG_RELAY_LADAR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -25286,6 +25326,8 @@ CONFIG_RACK_SCAN2D_SIM_TRUE!$CONFIG_RACK_SCAN2D_SIM_TRUE$ac_delim
 CONFIG_RACK_SCAN2D_SIM_FALSE!$CONFIG_RACK_SCAN2D_SIM_FALSE$ac_delim
 CONFIG_RACK_SCAN2D_LAB_TRUE!$CONFIG_RACK_SCAN2D_LAB_TRUE$ac_delim
 CONFIG_RACK_SCAN2D_LAB_FALSE!$CONFIG_RACK_SCAN2D_LAB_FALSE$ac_delim
+CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE!$CONFIG_RACK_OBJ_RECOG_IBEO_LUX_TRUE$ac_delim
+CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE!$CONFIG_RACK_OBJ_RECOG_IBEO_LUX_FALSE$ac_delim
 CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_TRUE!$CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_TRUE$ac_delim
 CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_FALSE!$CONFIG_RACK_OBJ_RECOG_RELAY_LADAR_FALSE$ac_delim
 CONFIG_RACK_DUMMY_ABC_TRUE!$CONFIG_RACK_DUMMY_ABC_TRUE$ac_delim
@@ -25298,8 +25340,6 @@ XENOMAI_LIBS!$XENOMAI_LIBS$ac_delim
 CONFIG_RACK_OS_XENOMAI_TRUE!$CONFIG_RACK_OS_XENOMAI_TRUE$ac_delim
 CONFIG_RACK_OS_XENOMAI_FALSE!$CONFIG_RACK_OS_XENOMAI_FALSE$ac_delim
 LINUX_CPPFLAGS!$LINUX_CPPFLAGS$ac_delim
-LINUX_LDFLAGS!$LINUX_LDFLAGS$ac_delim
-LINUX_LIBS!$LINUX_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -25341,6 +25381,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LINUX_LDFLAGS!$LINUX_LDFLAGS$ac_delim
+LINUX_LIBS!$LINUX_LIBS$ac_delim
 CONFIG_RACK_OS_LINUX_TRUE!$CONFIG_RACK_OS_LINUX_TRUE$ac_delim
 CONFIG_RACK_OS_LINUX_FALSE!$CONFIG_RACK_OS_LINUX_FALSE$ac_delim
 RTNET_CPPFLAGS!$RTNET_CPPFLAGS$ac_delim
@@ -25406,7 +25448,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 63; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 65; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
