make rack compile under linux without xenomai

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJNAME build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD JAR RACK_TARGET_ARCH CONFIG_RACK_BUILD_KMOD_TRUE CONFIG_RACK_BUILD_KMOD_FALSE XENO_USER_PREFIX XENO_LIBRARIES CONFIG_RACK_JAVA_TRUE CONFIG_RACK_JAVA_FALSE CONFIG_RACK_JAVA CONFIG_RACK_JAVA_GUI_TRUE CONFIG_RACK_JAVA_GUI_FALSE CONFIG_RACK_JAVA_GUI CONFIG_RACK_CAMERA_DCAM_TRUE CONFIG_RACK_CAMERA_DCAM_FALSE CONFIG_RACK_CAMERA_FILE_TRUE CONFIG_RACK_CAMERA_FILE_FALSE CONFIG_RACK_CAMERA_JPEG_TRUE CONFIG_RACK_CAMERA_JPEG_FALSE CONFIG_RACK_CAMERA_V4L_TRUE CONFIG_RACK_CAMERA_V4L_FALSE CONFIG_RACK_CHASSIS_PIONEER_TRUE CONFIG_RACK_CHASSIS_PIONEER_FALSE CONFIG_RACK_CHASSIS_SIM_TRUE CONFIG_RACK_CHASSIS_SIM_FALSE CONFIG_RACK_GPS_NMEA_TRUE CONFIG_RACK_GPS_NMEA_FALSE CONFIG_RACK_LADAR_HOKUYO_URG_TRUE CONFIG_RACK_LADAR_HOKUYO_URG_FALSE CONFIG_RACK_LADAR_IBEO_TRUE CONFIG_RACK_LADAR_IBEO_FALSE CONFIG_RACK_LADAR_SICK_LMS200_TRUE CONFIG_RACK_LADAR_SICK_LMS200_FALSE CONFIG_RACK_LADAR_SICK_S_TRUE CONFIG_RACK_LADAR_SICK_S_FALSE CONFIG_RACK_ODOMETRY_CHASSIS_TRUE CONFIG_RACK_ODOMETRY_CHASSIS_FALSE CONFIG_RACK_PILOT_JOYSTICK_TRUE CONFIG_RACK_PILOT_JOYSTICK_FALSE CONFIG_RACK_PILOT_WALL_FOLLOWING_TRUE CONFIG_RACK_PILOT_WALL_FOLLOWING_FALSE CONFIG_RACK_POSITION_TRUE CONFIG_RACK_POSITION_FALSE CONFIG_RACK_SCAN2D_TRUE CONFIG_RACK_SCAN2D_FALSE CONFIG_RACK_SCAN2D_MERGE_TRUE CONFIG_RACK_SCAN2D_MERGE_FALSE CONFIG_RACK_SCAN2D_SIM_TRUE CONFIG_RACK_SCAN2D_SIM_FALSE CONFIG_RACK_DUMMY_ABC_TRUE CONFIG_RACK_DUMMY_ABC_FALSE CONFIG_DATALOG_REC_TRUE CONFIG_DATALOG_REC_FALSE XENOMAI_CPPFLAGS XENOMAI_LDFLAGS XENOMAI_LIBS RTNET_CPPFLAGS CONFIG_RACK_RTNET_SUPPORT_TRUE CONFIG_RACK_RTNET_SUPPORT_FALSE LIBRAW1394_CPPFLAGS LIBRAW1394_LDFLAGS LIBRAW1394_LIBS CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE LIBDC1394_CPPFLAGS LIBDC1394_LDFLAGS LIBDC1394_LIBS CONFIG_RACK_LIBDC1394_SUPPORT_TRUE CONFIG_RACK_LIBDC1394_SUPPORT_FALSE LIBJPEG_CPPFLAGS LIBJPEG_LDFLAGS LIBJPEG_LIBS CONFIG_RACK_LIBJPEG_SUPPORT_TRUE CONFIG_RACK_LIBJPEG_SUPPORT_FALSE LIBPNG_CPPFLAGS LIBPNG_LDFLAGS LIBPNG_LIBS CONFIG_LIBPNG_TRUE CONFIG_LIBPNG_FALSE CONFIG_RACK_LIBPNG_SUPPORT_TRUE CONFIG_RACK_LIBPNG_SUPPORT_FALSE OPENCV_CPPFLAGS OPENCV_LDFLAGS OPENCV_LIBS CONFIG_OPENCV_TRUE CONFIG_OPENCV_FALSE CONFIG_RACK_OPENCV_SUPPORT_TRUE CONFIG_RACK_OPENCV_SUPPORT_FALSE RACK_GLOBAL_CPPFLAGS RACK_GLOBAL_LDFLAGS RACK_SUPPORTS RACK_CPPFLAGS RACK_LDFLAGS RACK_LIBS RACK_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT CONFIG_RACK_DOC_DOX_TRUE CONFIG_RACK_DOC_DOX_FALSE DOXYGEN_SHOW_INCLUDE_FILES CROSS_COMPILE RACK_MODULE_EXT RACK_KBUILD_ENV RACK_KBUILD_CMD RACK_KBUILD_CLEAN RACK_KBUILD_DISTCLEAN RACK_MODULE_DIR RACK_KMOD_CFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJNAME build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL CCAS CCASFLAGS LD JAR RACK_TARGET_ARCH CONFIG_RACK_BUILD_KMOD_TRUE CONFIG_RACK_BUILD_KMOD_FALSE XENO_USER_PREFIX XENO_LIBRARIES CONFIG_RACK_JAVA_TRUE CONFIG_RACK_JAVA_FALSE CONFIG_RACK_JAVA CONFIG_RACK_JAVA_GUI_TRUE CONFIG_RACK_JAVA_GUI_FALSE CONFIG_RACK_JAVA_GUI CONFIG_RACK_CAMERA_DCAM_TRUE CONFIG_RACK_CAMERA_DCAM_FALSE CONFIG_RACK_CAMERA_FILE_TRUE CONFIG_RACK_CAMERA_FILE_FALSE CONFIG_RACK_CAMERA_JPEG_TRUE CONFIG_RACK_CAMERA_JPEG_FALSE CONFIG_RACK_CAMERA_V4L_TRUE CONFIG_RACK_CAMERA_V4L_FALSE CONFIG_RACK_CHASSIS_PIONEER_TRUE CONFIG_RACK_CHASSIS_PIONEER_FALSE CONFIG_RACK_CHASSIS_SIM_TRUE CONFIG_RACK_CHASSIS_SIM_FALSE CONFIG_RACK_GPS_NMEA_TRUE CONFIG_RACK_GPS_NMEA_FALSE CONFIG_RACK_LADAR_HOKUYO_URG_TRUE CONFIG_RACK_LADAR_HOKUYO_URG_FALSE CONFIG_RACK_LADAR_IBEO_TRUE CONFIG_RACK_LADAR_IBEO_FALSE CONFIG_RACK_LADAR_SICK_LMS200_TRUE CONFIG_RACK_LADAR_SICK_LMS200_FALSE CONFIG_RACK_LADAR_SICK_S_TRUE CONFIG_RACK_LADAR_SICK_S_FALSE CONFIG_RACK_ODOMETRY_CHASSIS_TRUE CONFIG_RACK_ODOMETRY_CHASSIS_FALSE CONFIG_RACK_PILOT_JOYSTICK_TRUE CONFIG_RACK_PILOT_JOYSTICK_FALSE CONFIG_RACK_PILOT_WALL_FOLLOWING_TRUE CONFIG_RACK_PILOT_WALL_FOLLOWING_FALSE CONFIG_RACK_POSITION_TRUE CONFIG_RACK_POSITION_FALSE CONFIG_RACK_SCAN2D_TRUE CONFIG_RACK_SCAN2D_FALSE CONFIG_RACK_SCAN2D_MERGE_TRUE CONFIG_RACK_SCAN2D_MERGE_FALSE CONFIG_RACK_SCAN2D_SIM_TRUE CONFIG_RACK_SCAN2D_SIM_FALSE CONFIG_RACK_DUMMY_ABC_TRUE CONFIG_RACK_DUMMY_ABC_FALSE CONFIG_DATALOG_REC_TRUE CONFIG_DATALOG_REC_FALSE XENOMAI_CPPFLAGS XENOMAI_LDFLAGS XENOMAI_LIBS CONFIG_RACK_OS_XENOMAI_TRUE CONFIG_RACK_OS_XENOMAI_FALSE LINUX_CPPFLAGS LINUX_LDFLAGS LINUX_LIBS CONFIG_RACK_OS_LINUX_TRUE CONFIG_RACK_OS_LINUX_FALSE RTNET_CPPFLAGS CONFIG_RACK_RTNET_SUPPORT_TRUE CONFIG_RACK_RTNET_SUPPORT_FALSE LIBRAW1394_CPPFLAGS LIBRAW1394_LDFLAGS LIBRAW1394_LIBS CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE LIBDC1394_CPPFLAGS LIBDC1394_LDFLAGS LIBDC1394_LIBS CONFIG_RACK_LIBDC1394_SUPPORT_TRUE CONFIG_RACK_LIBDC1394_SUPPORT_FALSE LIBJPEG_CPPFLAGS LIBJPEG_LDFLAGS LIBJPEG_LIBS CONFIG_RACK_LIBJPEG_SUPPORT_TRUE CONFIG_RACK_LIBJPEG_SUPPORT_FALSE LIBPNG_CPPFLAGS LIBPNG_LDFLAGS LIBPNG_LIBS CONFIG_LIBPNG_TRUE CONFIG_LIBPNG_FALSE CONFIG_RACK_LIBPNG_SUPPORT_TRUE CONFIG_RACK_LIBPNG_SUPPORT_FALSE OPENCV_CPPFLAGS OPENCV_LDFLAGS OPENCV_LIBS CONFIG_OPENCV_TRUE CONFIG_OPENCV_FALSE CONFIG_RACK_OPENCV_SUPPORT_TRUE CONFIG_RACK_OPENCV_SUPPORT_FALSE RACK_GLOBAL_CPPFLAGS RACK_GLOBAL_LDFLAGS RACK_CPPFLAGS RACK_LDFLAGS RACK_LIBS RACK_SUPPORTS RACK_MAYBE_DOCDIR DOXYGEN DOXYGEN_HAVE_DOT CONFIG_RACK_DOC_DOX_TRUE CONFIG_RACK_DOC_DOX_FALSE DOXYGEN_SHOW_INCLUDE_FILES CROSS_COMPILE RACK_MODULE_EXT RACK_KBUILD_ENV RACK_KBUILD_CMD RACK_KBUILD_CLEAN RACK_KBUILD_DISTCLEAN RACK_MODULE_DIR RACK_KMOD_CFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19135,6 +19135,11 @@ echo "$as_me: error: You must supply an argument to --with-xeno-user-dir." >&2;}
 
 fi;
 
+XENO_USER_PREFIX=""
+XENO_LIBRARIES=""
+
+if test "${CONFIG_RACK_XENOMAIDIR}" \!= "" ; then
+
 
 echo "$as_me:$LINENO: checking for Xenomai userspace installation" >&5
 echo $ECHO_N "checking for Xenomai userspace installation... $ECHO_C" >&6
@@ -19176,6 +19181,8 @@ echo "${ECHO_T}${XENO_VERSION_PRE}" >&6
 
 
 XENO_LIBRARIES="`${XENO_USER_CONFIG} --library-dir`"
+
+fi
 
 
 
@@ -20062,17 +20069,66 @@ RACK_KMOD_CFLAGS=""
 RACK_SUPPORTS=""
 
 
+echo "$as_me:$LINENO: checking target os xenomai" >&5
+echo $ECHO_N "checking target os xenomai... $ECHO_C" >&6
+echo "$as_me:$LINENO: result: ${CONFIG_RACK_OS_XENOMAI}" >&5
+echo "${ECHO_T}${CONFIG_RACK_OS_XENOMAI}" >&6
+
+XENOMAI_CPPFLAGS=""
+XENOMAI_LDFLAGS=""
+XENOMAI_LIBS=""
+
+if test x"${CONFIG_RACK_OS_XENOMAI}" = x"y"; then
+
 XENOMAI_CPPFLAGS="`${XENO_USER_CONFIG} --xeno-cflags` -D__XENO__"
 XENOMAI_LDFLAGS="`${XENO_USER_CONFIG} --xeno-ldflags`"
 XENOMAI_LIBS="-lnative -lrtdm"
 
+fi
 
 
 
 
 
-echo "$as_me:$LINENO: checking rtnet support is needed" >&5
-echo $ECHO_N "checking rtnet support is needed... $ECHO_C" >&6
+
+
+if test x"${CONFIG_RACK_OS_XENOMAI}" = "xy"; then
+  CONFIG_RACK_OS_XENOMAI_TRUE=
+  CONFIG_RACK_OS_XENOMAI_FALSE='#'
+else
+  CONFIG_RACK_OS_XENOMAI_TRUE='#'
+  CONFIG_RACK_OS_XENOMAI_FALSE=
+fi
+
+
+
+echo "$as_me:$LINENO: checking target os linux" >&5
+echo $ECHO_N "checking target os linux... $ECHO_C" >&6
+echo "$as_me:$LINENO: result: ${CONFIG_RACK_OS_LINUX}" >&5
+echo "${ECHO_T}${CONFIG_RACK_OS_LINUX}" >&6
+
+LINUX_CPPFLAGS=""
+LINUX_LDFLAGS=""
+LINUX_LIBS="-lpthread"
+
+
+
+
+
+
+
+if test x"${CONFIG_RACK_O_LINUX}" = "xy"; then
+  CONFIG_RACK_OS_LINUX_TRUE=
+  CONFIG_RACK_OS_LINUX_FALSE='#'
+else
+  CONFIG_RACK_OS_LINUX_TRUE='#'
+  CONFIG_RACK_OS_LINUX_FALSE=
+fi
+
+
+
+echo "$as_me:$LINENO: checking rtnet support" >&5
+echo $ECHO_N "checking rtnet support... $ECHO_C" >&6
 echo "$as_me:$LINENO: result: ${CONFIG_RACK_RTNET_SUPPORT}" >&5
 echo "${ECHO_T}${CONFIG_RACK_RTNET_SUPPORT}" >&6
 
@@ -21958,24 +22014,33 @@ fi
 
 
 
-
 RACK_GLOBAL_CPPFLAGS="-Wall -pipe -O2 -fstrict-aliasing"
-
-
-
 RACK_GLOBAL_LDFLAGS="--export-dynamic"
 
 
 
-RACK_SUPPORTS="${PROJNAME} ${RACK_SUPPORTS}"
 
+if test x"${CONFIG_RACK_OS_XENOMAI}" = x"y"; then
 
 RACK_CPPFLAGS="-D__IN_RACK__ -I\${top_srcdir} -I\${top_builddir} ${XENOMAI_CPPFLAGS} ${RACK_GLOBAL_CPPFLAGS}"
 RACK_LDFLAGS="-L\$(top_builddir)/main/lib/.libs ${XENOMAI_LDFLAGS} ${RACK_GLOBAL_LDFLAGS}"
 RACK_LIBS="-l${PROJNAME} ${XENOMAI_LIBS}"
 
+else
+
+RACK_CPPFLAGS="-D__IN_RACK__ -I\${top_srcdir} -I\${top_builddir} ${LINUX_CPPFLAGS} ${RACK_GLOBAL_CPPFLAGS}"
+RACK_LDFLAGS="-L\$(top_builddir)/main/lib/.libs ${LINUX_LDFLAGS} ${RACK_GLOBAL_LDFLAGS}"
+RACK_LIBS="-l${PROJNAME} ${LINUX_LIBS}"
+
+fi
 
 
+
+
+
+
+
+RACK_SUPPORTS="${PROJNAME} ${RACK_SUPPORTS}"
 
 
 
@@ -22528,6 +22593,20 @@ if test -z "${CONFIG_DATALOG_REC_TRUE}" && test -z "${CONFIG_DATALOG_REC_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_DATALOG_REC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONFIG_DATALOG_REC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RACK_OS_XENOMAI_TRUE}" && test -z "${CONFIG_RACK_OS_XENOMAI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_OS_XENOMAI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_OS_XENOMAI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CONFIG_RACK_OS_LINUX_TRUE}" && test -z "${CONFIG_RACK_OS_LINUX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_OS_LINUX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_OS_LINUX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23306,6 +23385,13 @@ s,@CONFIG_DATALOG_REC_FALSE@,$CONFIG_DATALOG_REC_FALSE,;t t
 s,@XENOMAI_CPPFLAGS@,$XENOMAI_CPPFLAGS,;t t
 s,@XENOMAI_LDFLAGS@,$XENOMAI_LDFLAGS,;t t
 s,@XENOMAI_LIBS@,$XENOMAI_LIBS,;t t
+s,@CONFIG_RACK_OS_XENOMAI_TRUE@,$CONFIG_RACK_OS_XENOMAI_TRUE,;t t
+s,@CONFIG_RACK_OS_XENOMAI_FALSE@,$CONFIG_RACK_OS_XENOMAI_FALSE,;t t
+s,@LINUX_CPPFLAGS@,$LINUX_CPPFLAGS,;t t
+s,@LINUX_LDFLAGS@,$LINUX_LDFLAGS,;t t
+s,@LINUX_LIBS@,$LINUX_LIBS,;t t
+s,@CONFIG_RACK_OS_LINUX_TRUE@,$CONFIG_RACK_OS_LINUX_TRUE,;t t
+s,@CONFIG_RACK_OS_LINUX_FALSE@,$CONFIG_RACK_OS_LINUX_FALSE,;t t
 s,@RTNET_CPPFLAGS@,$RTNET_CPPFLAGS,;t t
 s,@CONFIG_RACK_RTNET_SUPPORT_TRUE@,$CONFIG_RACK_RTNET_SUPPORT_TRUE,;t t
 s,@CONFIG_RACK_RTNET_SUPPORT_FALSE@,$CONFIG_RACK_RTNET_SUPPORT_FALSE,;t t
@@ -23340,10 +23426,10 @@ s,@CONFIG_RACK_OPENCV_SUPPORT_TRUE@,$CONFIG_RACK_OPENCV_SUPPORT_TRUE,;t t
 s,@CONFIG_RACK_OPENCV_SUPPORT_FALSE@,$CONFIG_RACK_OPENCV_SUPPORT_FALSE,;t t
 s,@RACK_GLOBAL_CPPFLAGS@,$RACK_GLOBAL_CPPFLAGS,;t t
 s,@RACK_GLOBAL_LDFLAGS@,$RACK_GLOBAL_LDFLAGS,;t t
-s,@RACK_SUPPORTS@,$RACK_SUPPORTS,;t t
 s,@RACK_CPPFLAGS@,$RACK_CPPFLAGS,;t t
 s,@RACK_LDFLAGS@,$RACK_LDFLAGS,;t t
 s,@RACK_LIBS@,$RACK_LIBS,;t t
+s,@RACK_SUPPORTS@,$RACK_SUPPORTS,;t t
 s,@RACK_MAYBE_DOCDIR@,$RACK_MAYBE_DOCDIR,;t t
 s,@DOXYGEN@,$DOXYGEN,;t t
 s,@DOXYGEN_HAVE_DOT@,$DOXYGEN_HAVE_DOT,;t t
