added new module ClockDcf77MbgC51

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -908,6 +908,8 @@ CONFIG_RACK_CHASSIS_ROOMBA_TRUE
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE
+CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE
+CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE
 CONFIG_RACK_GPS_NMEA_TRUE
 CONFIG_RACK_GPS_NMEA_FALSE
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE
@@ -1637,6 +1639,8 @@ Optional Features:
   --enable-chassis-roomba building ChassisRoomba
   --enable-clock-dcf77-emc-pro
                           building ClockDcf77EmcPro
+  --enable-clock-dcf77-mbg-c51
+                          building ClockDcf77MbgC51
   --enable-gps-nmea       building GpsNmea
   --enable-ladar-hokuyo-urg
                           building LadarHokuyoUrg
@@ -4609,7 +4613,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4612 "configure"' > conftest.$ac_ext
+  echo '#line 4616 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7346,11 +7350,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7349: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7353: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7353: \$? = $ac_status" >&5
+   echo "$as_me:7357: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7636,11 +7640,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7639: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7643: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7643: \$? = $ac_status" >&5
+   echo "$as_me:7647: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7740,11 +7744,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7743: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7747: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7747: \$? = $ac_status" >&5
+   echo "$as_me:7751: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10089,7 +10093,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10092 "configure"
+#line 10096 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10189,7 +10193,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10192 "configure"
+#line 10196 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12609,11 +12613,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12612: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12616: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12616: \$? = $ac_status" >&5
+   echo "$as_me:12620: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12713,11 +12717,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12716: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12720: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12720: \$? = $ac_status" >&5
+   echo "$as_me:12724: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14275,11 +14279,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14278: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14282: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14282: \$? = $ac_status" >&5
+   echo "$as_me:14286: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14379,11 +14383,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14382: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14386: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14386: \$? = $ac_status" >&5
+   echo "$as_me:14390: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16566,11 +16570,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16569: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16573: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16573: \$? = $ac_status" >&5
+   echo "$as_me:16577: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16856,11 +16860,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16859: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16863: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16863: \$? = $ac_status" >&5
+   echo "$as_me:16867: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16960,11 +16964,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16963: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16967: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16967: \$? = $ac_status" >&5
+   echo "$as_me:16971: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20721,6 +20725,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build ClockDcf77MbgC51" >&5
+echo $ECHO_N "checking build ClockDcf77MbgC51... $ECHO_C" >&6; }
+# Check whether --enable-clock-dcf77-mbg-c51 was given.
+if test "${enable_clock_dcf77_mbg_c51+set}" = set; then
+  enableval=$enable_clock_dcf77_mbg_c51; case "$enableval" in
+        y | yes) CONFIG_RACK_CLOCK_DCF77_MBG_C51=y ;;
+        *) CONFIG_RACK_CLOCK_DCF77_MBG_C51=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_CLOCK_DCF77_MBG_C51:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_CLOCK_DCF77_MBG_C51:-n}" >&6; }
+ if test "$CONFIG_RACK_CLOCK_DCF77_MBG_C51" = "y"; then
+  CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE=
+  CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE='#'
+else
+  CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE='#'
+  CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE=
+fi
+
+if test "$CONFIG_RACK_CLOCK_DCF77_MBG_C51" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_CLOCK_DCF77_MBG_C51 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build GpsNmea" >&5
 echo $ECHO_N "checking build GpsNmea... $ECHO_C" >&6; }
 # Check whether --enable-gps-nmea was given.
@@ -23620,6 +23653,13 @@ echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_DCF77_EMC_PRO\" was never d
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE}" && test -z "${CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CLOCK_DCF77_MBG_C51\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_DCF77_MBG_C51\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RACK_GPS_NMEA_TRUE}" && test -z "${CONFIG_RACK_GPS_NMEA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_GPS_NMEA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24601,6 +24641,8 @@ CONFIG_RACK_CHASSIS_ROOMBA_TRUE!$CONFIG_RACK_CHASSIS_ROOMBA_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE!$CONFIG_RACK_CHASSIS_ROOMBA_FALSE$ac_delim
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE$ac_delim
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE$ac_delim
+CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE$ac_delim
+CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE$ac_delim
 CONFIG_RACK_GPS_NMEA_TRUE!$CONFIG_RACK_GPS_NMEA_TRUE$ac_delim
 CONFIG_RACK_GPS_NMEA_FALSE!$CONFIG_RACK_GPS_NMEA_FALSE$ac_delim
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE!$CONFIG_RACK_LADAR_HOKUYO_URG_TRUE$ac_delim
@@ -24653,8 +24695,6 @@ RTNET_CPPFLAGS!$RTNET_CPPFLAGS$ac_delim
 CONFIG_RACK_RTNET_SUPPORT_TRUE!$CONFIG_RACK_RTNET_SUPPORT_TRUE$ac_delim
 CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
 LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
-LIBRAW1394_LDFLAGS!$LIBRAW1394_LDFLAGS$ac_delim
-LIBRAW1394_LIBS!$LIBRAW1394_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24696,6 +24736,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LIBRAW1394_LDFLAGS!$LIBRAW1394_LDFLAGS$ac_delim
+LIBRAW1394_LIBS!$LIBRAW1394_LIBS$ac_delim
 CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE!$CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE$ac_delim
 CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE!$CONFIG_RACK_LIBRAW1394_SUPPORT_FALSE$ac_delim
 LIBDC1394_CPPFLAGS!$LIBDC1394_CPPFLAGS$ac_delim
@@ -24746,7 +24788,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 48; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
