added new module ClockSystem

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -910,6 +910,8 @@ CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE
+CONFIG_RACK_CLOCK_SYSTEM_TRUE
+CONFIG_RACK_CLOCK_SYSTEM_FALSE
 CONFIG_RACK_GPS_NMEA_TRUE
 CONFIG_RACK_GPS_NMEA_FALSE
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE
@@ -1641,6 +1643,7 @@ Optional Features:
                           building ClockDcf77EmcPro
   --enable-clock-dcf77-mbg-c51
                           building ClockDcf77MbgC51
+  --enable-clock-system   building ClockSystem
   --enable-gps-nmea       building GpsNmea
   --enable-ladar-hokuyo-urg
                           building LadarHokuyoUrg
@@ -5085,7 +5088,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5088 "configure"' > conftest.$ac_ext
+  echo '#line 5091 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7350,11 +7353,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7353: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7356: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7357: \$? = $ac_status" >&5
+   echo "$as_me:7360: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7640,11 +7643,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7643: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7646: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7647: \$? = $ac_status" >&5
+   echo "$as_me:7650: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7744,11 +7747,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7747: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7750: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7751: \$? = $ac_status" >&5
+   echo "$as_me:7754: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10093,7 +10096,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10096 "configure"
+#line 10099 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10193,7 +10196,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10196 "configure"
+#line 10199 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12613,11 +12616,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12616: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12619: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12620: \$? = $ac_status" >&5
+   echo "$as_me:12623: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12717,11 +12720,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12720: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12723: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12724: \$? = $ac_status" >&5
+   echo "$as_me:12727: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14279,11 +14282,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14282: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14285: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14286: \$? = $ac_status" >&5
+   echo "$as_me:14289: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14383,11 +14386,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14386: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14389: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14390: \$? = $ac_status" >&5
+   echo "$as_me:14393: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16570,11 +16573,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16573: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16576: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16577: \$? = $ac_status" >&5
+   echo "$as_me:16580: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16860,11 +16863,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16866: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16867: \$? = $ac_status" >&5
+   echo "$as_me:16870: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16964,11 +16967,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16967: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16970: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16971: \$? = $ac_status" >&5
+   echo "$as_me:16974: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20754,6 +20757,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build ClockSystem" >&5
+echo $ECHO_N "checking build ClockSystem... $ECHO_C" >&6; }
+# Check whether --enable-clock-system was given.
+if test "${enable_clock_system+set}" = set; then
+  enableval=$enable_clock_system; case "$enableval" in
+        y | yes) CONFIG_RACK_CLOCK_SYSTEM=y ;;
+        *) CONFIG_RACK_CLOCK_SYSTEM=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_CLOCK_SYSTEM:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_CLOCK_SYSTEM:-n}" >&6; }
+ if test "$CONFIG_RACK_CLOCK_SYSTEM" = "y"; then
+  CONFIG_RACK_CLOCK_SYSTEM_TRUE=
+  CONFIG_RACK_CLOCK_SYSTEM_FALSE='#'
+else
+  CONFIG_RACK_CLOCK_SYSTEM_TRUE='#'
+  CONFIG_RACK_CLOCK_SYSTEM_FALSE=
+fi
+
+if test "$CONFIG_RACK_CLOCK_SYSTEM" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_CLOCK_SYSTEM 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build GpsNmea" >&5
 echo $ECHO_N "checking build GpsNmea... $ECHO_C" >&6; }
 # Check whether --enable-gps-nmea was given.
@@ -23659,6 +23691,13 @@ echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_DCF77_MBG_C51\" was never d
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RACK_CLOCK_SYSTEM_TRUE}" && test -z "${CONFIG_RACK_CLOCK_SYSTEM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CLOCK_SYSTEM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_CLOCK_SYSTEM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RACK_GPS_NMEA_TRUE}" && test -z "${CONFIG_RACK_GPS_NMEA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_GPS_NMEA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24642,6 +24681,8 @@ CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE$ac_de
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_FALSE$ac_delim
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_TRUE$ac_delim
 CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE!$CONFIG_RACK_CLOCK_DCF77_MBG_C51_FALSE$ac_delim
+CONFIG_RACK_CLOCK_SYSTEM_TRUE!$CONFIG_RACK_CLOCK_SYSTEM_TRUE$ac_delim
+CONFIG_RACK_CLOCK_SYSTEM_FALSE!$CONFIG_RACK_CLOCK_SYSTEM_FALSE$ac_delim
 CONFIG_RACK_GPS_NMEA_TRUE!$CONFIG_RACK_GPS_NMEA_TRUE$ac_delim
 CONFIG_RACK_GPS_NMEA_FALSE!$CONFIG_RACK_GPS_NMEA_FALSE$ac_delim
 CONFIG_RACK_LADAR_HOKUYO_URG_TRUE!$CONFIG_RACK_LADAR_HOKUYO_URG_TRUE$ac_delim
@@ -24692,8 +24733,6 @@ CONFIG_RACK_OS_LINUX_TRUE!$CONFIG_RACK_OS_LINUX_TRUE$ac_delim
 CONFIG_RACK_OS_LINUX_FALSE!$CONFIG_RACK_OS_LINUX_FALSE$ac_delim
 RTNET_CPPFLAGS!$RTNET_CPPFLAGS$ac_delim
 CONFIG_RACK_RTNET_SUPPORT_TRUE!$CONFIG_RACK_RTNET_SUPPORT_TRUE$ac_delim
-CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
-LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24735,6 +24774,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
+LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
 LIBRAW1394_LDFLAGS!$LIBRAW1394_LDFLAGS$ac_delim
 LIBRAW1394_LIBS!$LIBRAW1394_LIBS$ac_delim
 CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE!$CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE$ac_delim
@@ -24787,7 +24828,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
