New module ChassisUsarsim added

diff --git a/rack/configure b/rack/configure
--- a/rack/configure
+++ b/rack/configure
@@ -904,6 +904,8 @@ CONFIG_RACK_CHASSIS_ER1_TRUE
 CONFIG_RACK_CHASSIS_ER1_FALSE
 CONFIG_RACK_CHASSIS_SIM_TRUE
 CONFIG_RACK_CHASSIS_SIM_FALSE
+CONFIG_RACK_CHASSIS_USARSIM_TRUE
+CONFIG_RACK_CHASSIS_USARSIM_FALSE
 CONFIG_RACK_CHASSIS_ROOMBA_TRUE
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE
@@ -1636,6 +1638,8 @@ Optional Features:
                           building ChassisPioneer
   --enable-chassis-er1    building ChassisEr1
   --enable-chassis-sim    building ChassisSim
+  --enable-chassis-usarsim
+                          building ChassisUsarsim
   --enable-chassis-roomba building ChassisRoomba
   --enable-clock-dcf77-emc-pro
                           building ClockDcf77EmcPro
@@ -5085,7 +5089,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5088 "configure"' > conftest.$ac_ext
+  echo '#line 5092 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7350,11 +7354,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7353: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7357: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7357: \$? = $ac_status" >&5
+   echo "$as_me:7361: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7640,11 +7644,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7643: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7647: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7647: \$? = $ac_status" >&5
+   echo "$as_me:7651: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7744,11 +7748,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7747: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7751: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7751: \$? = $ac_status" >&5
+   echo "$as_me:7755: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10093,7 +10097,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10096 "configure"
+#line 10100 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10193,7 +10197,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10196 "configure"
+#line 10200 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12613,11 +12617,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12616: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12620: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12620: \$? = $ac_status" >&5
+   echo "$as_me:12624: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12717,11 +12721,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12720: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12724: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12724: \$? = $ac_status" >&5
+   echo "$as_me:12728: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14279,11 +14283,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14282: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14286: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14286: \$? = $ac_status" >&5
+   echo "$as_me:14290: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14383,11 +14387,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14386: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14390: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14390: \$? = $ac_status" >&5
+   echo "$as_me:14394: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16570,11 +16574,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16573: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16577: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16577: \$? = $ac_status" >&5
+   echo "$as_me:16581: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16860,11 +16864,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16867: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16867: \$? = $ac_status" >&5
+   echo "$as_me:16871: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16964,11 +16968,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16967: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16971: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16971: \$? = $ac_status" >&5
+   echo "$as_me:16975: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20667,6 +20671,35 @@ _ACEOF
 fi
 
 
+{ echo "$as_me:$LINENO: checking build ChassisUsarsim" >&5
+echo $ECHO_N "checking build ChassisUsarsim... $ECHO_C" >&6; }
+# Check whether --enable-chassis-usarsim was given.
+if test "${enable_chassis_usarsim+set}" = set; then
+  enableval=$enable_chassis_usarsim; case "$enableval" in
+        y | yes) CONFIG_RACK_CHASSIS_USARSIM=y ;;
+        *) CONFIG_RACK_CHASSIS_USARSIM=n ;;
+    esac
+fi
+
+{ echo "$as_me:$LINENO: result: ${CONFIG_RACK_CHASSIS_USARSIM:-n}" >&5
+echo "${ECHO_T}${CONFIG_RACK_CHASSIS_USARSIM:-n}" >&6; }
+ if test "$CONFIG_RACK_CHASSIS_USARSIM" = "y"; then
+  CONFIG_RACK_CHASSIS_USARSIM_TRUE=
+  CONFIG_RACK_CHASSIS_USARSIM_FALSE='#'
+else
+  CONFIG_RACK_CHASSIS_USARSIM_TRUE='#'
+  CONFIG_RACK_CHASSIS_USARSIM_FALSE=
+fi
+
+if test "$CONFIG_RACK_CHASSIS_USARSIM" = "y"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define CONFIG_RACK_CHASSIS_USARSIM 1
+_ACEOF
+
+fi
+
+
 { echo "$as_me:$LINENO: checking build ChassisRoomba" >&5
 echo $ECHO_N "checking build ChassisRoomba... $ECHO_C" >&6; }
 # Check whether --enable-chassis-roomba was given.
@@ -23639,6 +23672,13 @@ echo "$as_me: error: conditional \"CONFIG_RACK_CHASSIS_SIM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${CONFIG_RACK_CHASSIS_USARSIM_TRUE}" && test -z "${CONFIG_RACK_CHASSIS_USARSIM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CHASSIS_USARSIM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CONFIG_RACK_CHASSIS_USARSIM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CONFIG_RACK_CHASSIS_ROOMBA_TRUE}" && test -z "${CONFIG_RACK_CHASSIS_ROOMBA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CONFIG_RACK_CHASSIS_ROOMBA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24637,6 +24677,8 @@ CONFIG_RACK_CHASSIS_ER1_TRUE!$CONFIG_RACK_CHASSIS_ER1_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_ER1_FALSE!$CONFIG_RACK_CHASSIS_ER1_FALSE$ac_delim
 CONFIG_RACK_CHASSIS_SIM_TRUE!$CONFIG_RACK_CHASSIS_SIM_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_SIM_FALSE!$CONFIG_RACK_CHASSIS_SIM_FALSE$ac_delim
+CONFIG_RACK_CHASSIS_USARSIM_TRUE!$CONFIG_RACK_CHASSIS_USARSIM_TRUE$ac_delim
+CONFIG_RACK_CHASSIS_USARSIM_FALSE!$CONFIG_RACK_CHASSIS_USARSIM_FALSE$ac_delim
 CONFIG_RACK_CHASSIS_ROOMBA_TRUE!$CONFIG_RACK_CHASSIS_ROOMBA_TRUE$ac_delim
 CONFIG_RACK_CHASSIS_ROOMBA_FALSE!$CONFIG_RACK_CHASSIS_ROOMBA_FALSE$ac_delim
 CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE!$CONFIG_RACK_CLOCK_DCF77_EMC_PRO_TRUE$ac_delim
@@ -24693,8 +24735,6 @@ CONFIG_RACK_OS_LINUX_TRUE!$CONFIG_RACK_OS_LINUX_TRUE$ac_delim
 CONFIG_RACK_OS_LINUX_FALSE!$CONFIG_RACK_OS_LINUX_FALSE$ac_delim
 RTNET_CPPFLAGS!$RTNET_CPPFLAGS$ac_delim
 CONFIG_RACK_RTNET_SUPPORT_TRUE!$CONFIG_RACK_RTNET_SUPPORT_TRUE$ac_delim
-CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
-LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -24736,6 +24776,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CONFIG_RACK_RTNET_SUPPORT_FALSE!$CONFIG_RACK_RTNET_SUPPORT_FALSE$ac_delim
+LIBRAW1394_CPPFLAGS!$LIBRAW1394_CPPFLAGS$ac_delim
 LIBRAW1394_LDFLAGS!$LIBRAW1394_LDFLAGS$ac_delim
 LIBRAW1394_LIBS!$LIBRAW1394_LIBS$ac_delim
 CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE!$CONFIG_RACK_LIBRAW1394_SUPPORT_TRUE$ac_delim
@@ -24788,7 +24830,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
